language: ruby
rvm:
  - 2.2.2
cache: bundler
bundler_args: "--without development"
sudo: false
env: DATABASE_URL=postgres://postgres@localhost/duse_api_test
before_script:
- psql -c 'create database duse_api_test;' -U postgres
- bundle exec rake db:migrate
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: 09c1d3d72c61abdbc3d9def5322f5dc1d97a59ba77a8146be8fc2520f47e227c
notifications:
  slack:
    secure: V8a+rUco+dyagwWUObjlM+k+YLKSfdAmmhOBiJEtN3qHcYC9cVpuHJUJzYUakQyHcOA9R0/Ob8JUQoMO4plhwttlqhFpQq1FIJD+goEGI8eECdd267Yhofa3nAMP4oqmKVcC9NOXHcqtP8Xi2tVPq3hypgt10jcpDQUBXU/l7Gc=
deploy:
  provider: heroku
  api_key:
    secure: EBb54/sfFUppPtekHCXH9gKnt4DXFlmYuP1FvR2PPXZAMAOImkCIPgkHB22tpl2DUIsQh0W/yL0QTQb1RJOo2LLVRKspzmyvQjPd9Sxvd2iBa/D4Qj9QgS4K7XufIJXQw2bdU1RMygAqh7Hubl13jnjdb3sm24CyTJChmlleE3w=
  app: duse
  run: "rake db:migrate"
  on:
    repo: duse-io/api
