language: ruby
rvm:
  - 2.1.5
cache: bundler
bundler_args: "--without development"
before_script:
- psql -c 'create database duse_api_test;' -U postgres
- cp config/database.yml.travis config/database.yml
before_install:
- sudo apt-get update && sudo apt-get install -qq libpq-dev postgresql-server-dev-9.3
addons:
  postgresql: '9.3'
notifications:
  slack:
    secure: V8a+rUco+dyagwWUObjlM+k+YLKSfdAmmhOBiJEtN3qHcYC9cVpuHJUJzYUakQyHcOA9R0/Ob8JUQoMO4plhwttlqhFpQq1FIJD+goEGI8eECdd267Yhofa3nAMP4oqmKVcC9NOXHcqtP8Xi2tVPq3hypgt10jcpDQUBXU/l7Gc=
deploy:
  provider: heroku
  api_key:
    secure: EBb54/sfFUppPtekHCXH9gKnt4DXFlmYuP1FvR2PPXZAMAOImkCIPgkHB22tpl2DUIsQh0W/yL0QTQb1RJOo2LLVRKspzmyvQjPd9Sxvd2iBa/D4Qj9QgS4K7XufIJXQw2bdU1RMygAqh7Hubl13jnjdb3sm24CyTJChmlleE3w=
  app: duse
  run: "rake migrate"
  on:
    repo: duse-io/api
