language: ruby
rvm:
  - 2.1.3
cache: bundler
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database duse_api_test;' -U postgres
  - sudo apt-get install -qq libpq-dev postgresql-server-dev-9.3
