language: ruby
rvm: 2.1.5
cache: bundler
bundler_args: "--without development"
env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/duse_api_test
    - PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDc+zhQWbwrBnG3gJgTClaBjaWo\nuA8T/KWzVywg+wT4NBXHO76a+i+/WgC4PpEnxyGJsZJoUFNTFqB8qF/ouC78gZZi\neYa/zxZQVpQmHl2H07xRwxxoO7nbAybUdvtjir9DbIzYIW4GK5KXXvXbfTJqte9x\n/hKIcP1ILK+hSyd+dwIDAQAB\n-----END PUBLIC KEY-----\n"
    - PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDc+zhQWbwrBnG3gJgTClaBjaWouA8T/KWzVywg+wT4NBXHO76a\n+i+/WgC4PpEnxyGJsZJoUFNTFqB8qF/ouC78gZZieYa/zxZQVpQmHl2H07xRwxxo\nO7nbAybUdvtjir9DbIzYIW4GK5KXXvXbfTJqte9x/hKIcP1ILK+hSyd+dwIDAQAB\nAoGBANj7eHU1V5Wrszdq9mgjy4NUcah0aqHGf3HUk8kikeOhSQ0jdeo45W9v0asY\nDHHRjvXkPY1d6iN44UbmEZ6yU7bbLm538JlHsdNE4vXxia3o5q6IQ9kLn10D7puP\nbFoRt8mIoicArOSY/Sk0/zsOZYkER4stxcywhK1HjzTHO+jxAkEA++pyKHpJ42zJ\nDyPW3XE0yZdLmrLfJ4P8Z9LAAbOsLBnGopJKajHnY4k5VOtEKozKdLAiPpHaocWz\ndcLddGuIuQJBAOCQYh1wf8T1Q+TOhYWguqtBMiEA3Dyrv56YlQ6FIzCqzB3BqsHW\nTTME0cqw6SXHV+qVmLHZgIArTxyAeDY5SK8CQQCYvnGTe3p7rAVI6ckpIbAJH3RX\nC2flNNEBPrbvETsuzj4zapI2S6XqI1Ug2TnOtuk20WkiGRvAhPgoSgwuv9j5AkAp\nlnOlMhVne2iUci7GHYsUdiF7fTZMQh5dl7JbGwr2U1sz0471EOQBI85adELpTS6Z\n8hRyM26Zzet7wssAd8FfAkAIbLQKr0+K65MnS1fLGsCHHddJ7IbXdbdeemY1Xu98\nk+0KoDpBlKhbvW4vH0bjKhDpRpAip8xhKeWtM0osu3O4\n-----END RSA PRIVATE KEY-----\n"
    - PASSWORD="tCdQhV+hkz7Xnp5+19HgO6eq0tXjPc7U//seMohpZrk="
before_script:
- psql -c 'create database duse_api_test;' -U postgres
before_install:
- sudo apt-get install -qq libpq-dev postgresql-server-dev-9.3
addons:
  postgresql: '9.3'
notifications:
  slack:
    secure: V8a+rUco+dyagwWUObjlM+k+YLKSfdAmmhOBiJEtN3qHcYC9cVpuHJUJzYUakQyHcOA9R0/Ob8JUQoMO4plhwttlqhFpQq1FIJD+goEGI8eECdd267Yhofa3nAMP4oqmKVcC9NOXHcqtP8Xi2tVPq3hypgt10jcpDQUBXU/l7Gc=
deploy:
  provider: heroku
  api_key:
    secure: EBb54/sfFUppPtekHCXH9gKnt4DXFlmYuP1FvR2PPXZAMAOImkCIPgkHB22tpl2DUIsQh0W/yL0QTQb1RJOo2LLVRKspzmyvQjPd9Sxvd2iBa/D4Qj9QgS4K7XufIJXQw2bdU1RMygAqh7Hubl13jnjdb3sm24CyTJChmlleE3w=
  app: duse
  run: "rake migrate"
  on:
    repo: duse-io/api
