files:
  image: ubuntu
db:
  image: postgres:9.4
  volumes_from:
    - files
  volumes:
    - /var/lib/postgresql/data/
  ports:
    - "5432"
  environment:
    - POSTGRES_USER=duse
    - POSTGRES_PASSWORD=supersave
web:
  build: .
  volumes:
    - .:/usr/src/app
  ports:
    - "5000:5000"
  links:
    - db
  env_file: .env

