files:
  image: ubuntu
db:
  image: postgres:9.4
  volumes_from:
    - files
  volumes:
    - /var/lib/postgresql/data/
  ports:
    - "5432"
  environment:
    - POSTGRES_USER=duse
    - POSTGRES_PASSWORD=supersave
web:
  build: .
  command: rackup -p 5000 --host 0.0.0.0
  volumes:
    - .:/usr/src/app
  ports:
    - "5000:5000"
  links:
    - db
  environment:
    - EMAIL=noreply@duse.io
    - SECRET_KEY=somesupersecretkey
    - DATABASE_URL=postgres://duse:supersave@db/duse

